do $$
begin
  if to_regclass('public.workout_entries') is not null
     and to_regclass('public.w_workout_entries') is null then
    alter table public.workout_entries rename to w_workout_entries;
  end if;
  if to_regclass('public.cardio_entries') is not null
     and to_regclass('public.w_cardio_entries') is null then
    alter table public.cardio_entries rename to w_cardio_entries;
  end if;
  if to_regclass('public.weekly_weights') is not null
     and to_regclass('public.w_weekly_weights') is null then
    alter table public.weekly_weights rename to w_weekly_weights;
  end if;
end
$$;

create table if not exists public.w_users (
  user_key text primary key,
  display_name text not null unique
);

insert into public.w_users (user_key, display_name)
values ('bill', 'Bill'), ('paulette', 'Paulette')
on conflict (user_key) do update set display_name = excluded.display_name;

alter table public.w_users enable row level security;

create table if not exists public.w_plan_starts (
  user_key text primary key,
  start_date date not null,
  started_at timestamptz not null
);

alter table public.w_plan_starts enable row level security;

create table if not exists public.w_workout_entries (
  id bigint generated by default as identity primary key,
  user_key text not null,
  week integer not null,
  day text not null,
  exercise_id text not null,
  set_number integer not null,
  resistance double precision not null,
  reps integer not null,
  too_easy boolean not null default false,
  completed_at timestamptz not null
);

create index if not exists idx_w_workout_entries_user_key
  on public.w_workout_entries (user_key);

create table if not exists public.w_cardio_entries (
  id bigint generated by default as identity primary key,
  user_key text not null,
  week integer not null,
  day text not null,
  minutes integer not null,
  resistance integer not null,
  completed_at timestamptz not null
);

create index if not exists idx_w_cardio_entries_user_key
  on public.w_cardio_entries (user_key);

create table if not exists public.w_weekly_weights (
  id bigint generated by default as identity primary key,
  user_key text not null,
  week integer not null,
  weight double precision not null,
  recorded_at timestamptz not null,
  constraint idx_w_weekly_weights_user_week unique (user_key, week)
);

alter table public.w_workout_entries enable row level security;
alter table public.w_cardio_entries enable row level security;
alter table public.w_weekly_weights enable row level security;

-- Upgrade existing installations as well as fresh databases.
alter table public.w_workout_entries
  add column if not exists too_easy boolean not null default false;
